### PR TITLE
Implement parcel ref search

### PR DESCRIPTION
**Pull request by djbingham**
https://eaflood.atlassian.net/browse/FCEP-73

### CODE REVIEW

**Review by neilbmclaughlin — DISMISSED** [review]
LGTM

**Review by jaucourt — DISMISSED** [review]
Looks good - it's been a long time since I've seen front end code not using any framework!

The only things I thought of were that you could use class rather than the prototype pattern, but this isn't well supported in IE, so probably best you went with prototype. Also, I tend not to use Array.forEach, because you get a minuscule performance bonus from using a normal for loop, but the code is more readable using forEach.

**Comment by djbingham** [comment]
> Looks good - it's been a long time since I've seen front end code not using any framework!
> 
> The only things I thought of were that you could use class rather than the prototype pattern, but this isn't well supported in IE, so probably best you went with prototype. Also, I tend not to use Array.forEach, because you get a minuscule performance bonus from using a normal for loop, but the code is more readable using forEach.

Thanks! It's been a long time since I've written front-end code without a framework! For a while I was almost convinced testing was never going to work without a build tool. Using `module.exports` breaks in the browser, `export default` breaks in Node. And then I had tests failing because `document` and `Event` don't exist in Node. So glad I stumbled across Jest's `testEnvironment` setting.

I agree with everything you said on `for` vs `forEach`. The performance gain with `for` doesn't seem worthwhile, especially given how little JS we're putting into the front end and the fact that it's only there as an enhancement, not a core feature.

**Comment by neilbmclaughlin** [comment]
The previous commit resolves the validation issue (it was failing validation as a result of the search input being posted).

I think it is good to merge but, given both @djbingham and myself have worked on it, it would be worth @jaucourt re-reviewing and approving.

**Review by jaucourt — APPROVED** [review]
LGTM

**Pull request merged**
